export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  image: string
  category: string
  popular: boolean
  spicy: boolean
  vegetarian: boolean
  available: boolean
  sizes?: { size: string; price: number; pax?: string }[]
}

export const fullMenu: MenuItem[] = [
  // Chicken Dishes
  {
    id: "ch001",
    name: "Chicken Wings in Bilao",
    description: "Crispy fried chicken wings served in traditional bilao, perfect for sharing",
    price: 435,
    image: "/chicken-wings.jpg",
    category: "chicken-dishes",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "18 pcs", price: 435 },
      { size: "24 pcs", price: 655 },
      { size: "36 pcs", price: 895 },
      { size: "Per tub (6 pcs)", price: 165 },
    ],
  },
  {
    id: "ch002",
    name: "Roasted Chicken",
    description: "Perfectly seasoned and roasted whole chicken, juicy and flavorful",
    price: 390,
    image: "/roasted-chicken.jpg",
    category: "chicken-dishes",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "Whole (Large)", price: 390 },
      { size: "Jumbo", price: 455 },
    ],
  },
  {
    id: "ch003",
    name: "Chicken Cordon Bleu",
    description: "Breaded chicken breast stuffed with ham and cheese, good for sharing",
    price: 899,
    image: "/cordon-bleu.jpg",
    category: "chicken-dishes",
    popular: false,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [{ size: "Good for 10 pax", price: 899 }],
  },

  // Pasta & Noodles
  {
    id: "pn001",
    name: "Baked Macaroni",
    description: "Creamy baked macaroni with cheese and meat sauce, comfort food at its best",
    price: 650,
    image: "/baked-macaroni.jpg",
    category: "pasta-noodles",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "Medium Tray", price: 650 },
      { size: "Large Tray", price: 800 },
      { size: "Per tub", price: 50 },
    ],
  },
  {
    id: "pn002",
    name: "Carbonara",
    description: "Rich and creamy pasta with bacon and parmesan cheese",
    price: 650,
    image: "/carbonara.jpg",
    category: "pasta-noodles",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "Medium Tray", price: 650 },
      { size: "Large Tray", price: 800 },
      { size: "Per tub", price: 50 },
    ],
  },
  {
    id: "pn003",
    name: "Cheesy Spaghetti",
    description: "Filipino-style sweet spaghetti with hotdogs and lots of cheese",
    price: 650,
    image: "/spaghetti.png",
    category: "pasta-noodles",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "Medium Tray", price: 650 },
      { size: "Large Tray", price: 800 },
      { size: "Per tub", price: 50 },
    ],
  },
  {
    id: "pn004",
    name: "Pancit Canton Guisado",
    description: "Stir-fried wheat noodles with vegetables and meat, a Filipino favorite",
    price: 650,
    image: "/pancit-canton.jpg",
    category: "pasta-noodles",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "Medium Tray", price: 650 },
      { size: "Large Tray", price: 850 },
    ],
  },
  {
    id: "pn005",
    name: "Pancit Bihon",
    description: "Traditional rice noodles stir-fried with vegetables and meat",
    price: 600,
    image: "/pancit-bihon.jpg",
    category: "pasta-noodles",
    popular: false,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "Medium Bilao", price: 600 },
      { size: "Large Bilao", price: 750 },
    ],
  },
  {
    id: "pn006",
    name: "Pancit Palabok",
    description: "Rice noodles with shrimp sauce, topped with eggs, chicharron, and tinapa flakes",
    price: 600,
    image: "/pancit-palabok.jpg",
    category: "pasta-noodles",
    popular: false,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "Medium Bilao", price: 600 },
      { size: "Large Bilao", price: 750 },
    ],
  },

  // Pork Dishes
  {
    id: "pk001",
    name: "Lechon Belly",
    description: "Crispy roasted pork belly, the ultimate Filipino celebration dish",
    price: 1600,
    image: "/lechon-belly.jpg",
    category: "pork-dishes",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "2 kg", price: 1600, pax: "8-10 pax" },
      { size: "3 kg", price: 2400, pax: "10-15 pax" },
      { size: "4 kg", price: 3200, pax: "15-20 pax" },
    ],
  },
  {
    id: "pk002",
    name: "Pork Platter",
    description: "Assorted pork dishes perfect for sharing with family and friends",
    price: 599,
    image: "/pork-platter.jpg",
    category: "pork-dishes",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "Good for 5 pax", price: 599 },
      { size: "Good for 10 pax", price: 899 },
    ],
  },
  {
    id: "pk003",
    name: "Crispy Pata",
    description: "Deep-fried pork leg, crispy outside and tender inside",
    price: 850,
    image: "/crispy-pata.jpg",
    category: "pork-dishes",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
  },
  {
    id: "pk004",
    name: "Lechon Ulo",
    description: "Roasted pig's head, a traditional Filipino delicacy",
    price: 2400,
    image: "/lechon-ulo.jpg",
    category: "pork-dishes",
    popular: false,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [{ size: "5-6 kilos", price: 2400 }],
  },
  {
    id: "pk005",
    name: "Kare-Kare (Bagnet)",
    description: "Traditional Filipino stew with bagnet in rich peanut sauce",
    price: 699,
    image: "/kare-kare.jpg",
    category: "pork-dishes",
    popular: false,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "5 pax", price: 699 },
      { size: "6-10 pax", price: 999 },
      { size: "10-15 pax", price: 1399 },
    ],
  },

  // Beef Dishes
  {
    id: "bf001",
    name: "Beef Platter",
    description: "Premium beef dishes arranged beautifully for special occasions",
    price: 799,
    image: "/beef-platter.jpg",
    category: "beef-dishes",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "Good for 5 pax", price: 799 },
      { size: "Good for 10 pax", price: 1050 },
    ],
  },
  {
    id: "bf002",
    name: "Kare-Kare (Ox Tripe)",
    description: "Traditional Filipino stew with ox tripe in rich peanut sauce",
    price: 699,
    image: "/kare-kare.jpg",
    category: "beef-dishes",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "5 pax", price: 699 },
      { size: "10 pax", price: 899 },
      { size: "15 pax", price: 1299 },
    ],
  },

  // Fish & Seafood Dishes
  {
    id: "fs001",
    name: "Boneless Baked Cheesy Bangus",
    description: "Deboned milkfish baked with cheese, a Filipino comfort food favorite",
    price: 350,
    image: "/baked-bangus.jpg",
    category: "fish-seafood",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "Medium", price: 350 },
      { size: "Large", price: 400 },
    ],
  },
  {
    id: "fs002",
    name: "Boneless Stuffed Inihaw na Bangus",
    description: "Grilled stuffed milkfish, deboned and filled with flavorful stuffing",
    price: 300,
    image: "/inihaw-bangus.jpg",
    category: "fish-seafood",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "Medium", price: 300 },
      { size: "Large", price: 350 },
    ],
  },
  {
    id: "fs003",
    name: "Relyeno Bangus",
    description: "Stuffed milkfish with vegetables and spices, a classic Filipino dish",
    price: 380,
    image: "/relyenong-bangus.jpg",
    category: "fish-seafood",
    popular: false,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [{ size: "Large", price: 380 }],
  },
  {
    id: "fs004",
    name: "Tuna",
    description: "Fresh tuna prepared to perfection, rich in flavor and nutrients",
    price: 699,
    image: "/tuna.jpg",
    category: "fish-seafood",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "5 pax", price: 699 },
      { size: "10 pax", price: 999 },
    ],
  },
  {
    id: "fs005",
    name: "Lapu-Lapu",
    description: "Premium grouper fish, cooked to highlight its natural sweetness",
    price: 999,
    image: "lapu-lapu.jpg",
    category: "fish-seafood",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "5 pax", price: 999 },
      { size: "10 pax", price: 999 },
    ],
  },
  {
    id: "fs006",
    name: "Crabs",
    description: "Fresh crabs cooked in savory sauce, perfect for seafood lovers",
    price: 799,
    image: "/crabs.jpg",
    category: "fish-seafood",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "5 pax", price: 799 },
      { size: "10 pax", price: 1050 },
    ],
  },
  {
    id: "fs007",
    name: "Shrimp",
    description: "Fresh shrimp prepared with aromatic spices and herbs",
    price: 799,
    image: "/shrimp.png",
    category: "fish-seafood",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "5 pax", price: 799 },
      { size: "10 pax", price: 1050 },
    ],
  },
  {
    id: "fs008",
    name: "Fish Fillet",
    description: "Tender fish fillet cooked to perfection with special seasoning",
    price: 799,
    image: "/fish-fillet.jpg",
    category: "fish-seafood",
    popular: false,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [{ size: "10 pax", price: 799 }],
  },
  {
    id: "fs009",
    name: "Salmon Belly",
    description: "Rich and fatty salmon belly, grilled or baked to perfection",
    price: 699,
    image: "/salmon-belly.jpg",
    category: "fish-seafood",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "5 pax", price: 699 },
      { size: "10 pax", price: 899 },
    ],
  },
  {
    id: "fs010",
    name: "Seafood Platter",
    description: "Assorted fresh seafood beautifully arranged for special occasions",
    price: 999,
    image: "/seafood-platter.jpg",
    category: "fish-seafood",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [
      { size: "6 pax", price: 999 },
      { size: "10 pax", price: 1399 },
      { size: "15 pax", price: 1899 },
    ],
  },

  // Side Dishes / Add-ons
  {
    id: "sd001",
    name: "Lumpia Shanghai",
    description: "Crispy spring rolls filled with seasoned ground pork and vegetables",
    price: 12,
    image: "/lumpia-shanghai.jpg",
    category: "side-dishes",
    popular: true,
    spicy: false,
    vegetarian: false,
    available: true,
    sizes: [{ size: "Per piece", price: 12 }],
  },
  {
    id: "sd002",
    name: "Lumpiang Sariwa",
    description: "Fresh spring rolls with vegetables and sweet peanut sauce",
    price: 45,
    image: "/lumpia-sariwa.jpg",
    category: "side-dishes",
    popular: false,
    spicy: false,
    vegetarian: true,
    available: true,
    sizes: [{ size: "Per piece", price: 45 }],
  },
  {
    id: "sd003",
    name: "Puto",
    description: "Traditional Filipino steamed rice cake, soft and slightly sweet",
    price: 7,
    image: "/puto.jpg",
    category: "side-dishes",
    popular: false,
    spicy: false,
    vegetarian: true,
    available: true,
    sizes: [{ size: "Per piece", price: 7 }],
  },
  {
    id: "sd004",
    name: "Kutsinta",
    description: "Brown rice cake with coconut, a classic Filipino kakanin",
    price: 7,
    image: "/kutsinta.jpg",
    category: "side-dishes",
    popular: false,
    spicy: false,
    vegetarian: true,
    available: true,
    sizes: [{ size: "Per piece", price: 7 }],
  },

  // Desserts
  {
    id: "ds001",
    name: "Fruit Salad",
    description: "Fresh mixed fruits with cream and condensed milk, a Filipino party favorite",
    price: 700,
    image: "/fruit-salad.jpg",
    category: "desserts",
    popular: true,
    spicy: false,
    vegetarian: true,
    available: true,
    sizes: [
      { size: "Medium Tray", price: 700 },
      { size: "Large Tray", price: 950 },
    ],
  },
  {
    id: "ds002",
    name: "Macaroni Salad",
    description: "Creamy macaroni salad with fruits and vegetables, perfect for celebrations",
    price: 700,
    image: "/macaroni-salad.jpg",
    category: "desserts",
    popular: true,
    spicy: false,
    vegetarian: true,
    available: true,
    sizes: [
      { size: "Medium Tray", price: 700 },
      { size: "Large Tray", price: 950 },
    ],
  },
  {
    id: "ds003",
    name: "Buko Pandan",
    description: "Young coconut strips with pandan-flavored gelatin in creamy sauce",
    price: 600,
    image: "/buko-pandan.jpg",
    category: "desserts",
    popular: true,
    spicy: false,
    vegetarian: true,
    available: true,
    sizes: [
      { size: "Medium Tray", price: 600 },
      { size: "Large Tray", price: 750 },
    ],
  },
  {
    id: "ds004",
    name: "Coffee Jelly",
    description: "Refreshing coffee-flavored gelatin dessert with cream",
    price: 600,
    image: "/coffee-jelly.jpg",
    category: "desserts",
    popular: false,
    spicy: false,
    vegetarian: true,
    available: true,
    sizes: [
      { size: "Medium Tray", price: 600 },
      { size: "Large Tray", price: 750 },
    ],
  },
  {
    id: "ds005",
    name: "Biko",
    description: "Traditional Filipino sticky rice cake with coconut and brown sugar",
    price: 750,
    image: "/biko.jpg",
    category: "desserts",
    popular: false,
    spicy: false,
    vegetarian: true,
    available: true,
    sizes: [
      { size: "Medium", price: 750 },
      { size: "Large", price: 800 },
    ],
  },
  {
    id: "ds006",
    name: "Maja",
    description: "Coconut pudding made with corn kernels, a beloved Filipino dessert",
    price: 750,
    image: "/maja.png",
    category: "desserts",
    popular: false,
    spicy: false,
    vegetarian: true,
    available: true,
    sizes: [
      { size: "Medium", price: 750 },
      { size: "Large", price: 800 },
    ],
  },
]

export const categories = [
  { id: "all", name: "All Items", count: fullMenu.length },
  {
    id: "chicken-dishes",
    name: "Chicken Dishes",
    count: fullMenu.filter((item) => item.category === "chicken-dishes").length,
  },
  {
    id: "pasta-noodles",
    name: "Pasta & Noodles",
    count: fullMenu.filter((item) => item.category === "pasta-noodles").length,
  },
  { id: "pork-dishes", name: "Pork Dishes", count: fullMenu.filter((item) => item.category === "pork-dishes").length },
  { id: "beef-dishes", name: "Beef Dishes", count: fullMenu.filter((item) => item.category === "beef-dishes").length },
  {
    id: "fish-seafood",
    name: "Fish & Seafood",
    count: fullMenu.filter((item) => item.category === "fish-seafood").length,
  },
  {
    id: "side-dishes",
    name: "Side Dishes",
    count: fullMenu.filter((item) => item.category === "side-dishes").length,
  },
  { id: "desserts", name: "Desserts", count: fullMenu.filter((item) => item.category === "desserts").length },
]

// Simplified menu for forms
export const menuItems = [
  { id: "ch001", name: "Chicken Wings in Bilao (18 pcs)", price: 435, category: "Chicken Dishes" },
  { id: "ch002", name: "Roasted Chicken (Whole Large)", price: 390, category: "Chicken Dishes" },
  { id: "ch003", name: "Chicken Cordon Bleu", price: 899, category: "Chicken Dishes" },
  { id: "pn001", name: "Baked Macaroni (Medium Tray)", price: 650, category: "Pasta & Noodles" },
  { id: "pn002", name: "Carbonara (Medium Tray)", price: 650, category: "Pasta & Noodles" },
  { id: "pn003", name: "Cheesy Spaghetti (Medium Tray)", price: 650, category: "Pasta & Noodles" },
  { id: "pn004", name: "Pancit Canton Guisado (Medium Tray)", price: 650, category: "Pasta & Noodles" },
  { id: "pk001", name: "Lechon Belly (2 kg)", price: 1600, category: "Pork Dishes" },
  { id: "pk002", name: "Pork Platter (5 pax)", price: 599, category: "Pork Dishes" },
  { id: "pk003", name: "Crispy Pata", price: 850, category: "Pork Dishes" },
  { id: "bf001", name: "Beef Platter (5 pax)", price: 799, category: "Beef Dishes" },
  { id: "fs001", name: "Boneless Baked Cheesy Bangus (Medium)", price: 350, category: "Fish & Seafood" },
  { id: "fs010", name: "Seafood Platter (6 pax)", price: 999, category: "Fish & Seafood" },
  { id: "sd001", name: "Lumpia Shanghai (per piece)", price: 12, category: "Side Dishes" },
  { id: "ds001", name: "Fruit Salad (Medium Tray)", price: 700, category: "Desserts" },
  { id: "ds003", name: "Buko Pandan (Medium Tray)", price: 600, category: "Desserts" },
]
